Traceback (most recent call last):
  File "/home/spraetor/lehre/prog/lecture/venv/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spraetor/lehre/prog/lecture/venv/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/spraetor/lehre/prog/lecture/venv/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spraetor/lehre/prog/lecture/venv/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/spraetor/lehre/prog/lecture/venv/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/spraetor/lehre/prog/lecture/venv/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/spraetor/lehre/prog/lecture/venv/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
mutable struct List2
  head::Float64
  tail::List2

  List2(head::Float64) = (l=new(); l.head=head; l.tail=l) # Lasse tail auf sich selbst zeigen
end
l = List2(1.0, List2(2.0, List2(3.0, List2(4.0))))
l.tail.tail.tail.tail = List2(5.0)
------------------


MethodError: no method matching List2(::Float64, ::List2)
The type `List2` exists, but no method is defined for this combination of argument types when trying to construct it.

[0mClosest candidates are:
[0m  List2(::Float64)
[0m[90m   @[39m [35mMain[39m [90m[4mIn[6]:5[24m[39m


Stacktrace:
 [1] top-level scope
[90m   @[39m [90m[4mIn[6]:7[24m[39m

